apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scaletestapp
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: scaletestapp
  endpoints:
    - port: web
      path: /metrics
      interval: 15s